load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["root.go"],
    importpath = "github.com/neticdk/contour-jwt-auth/pkg/cmd",
    visibility = ["//visibility:public"],
)
