name: Continuous Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - run: bazel build //...
